spring:
  application:
    name: service_book
  config:
    import:
      - optional:file:./env/.env.dev[.properties]
      - optional:file:../env/.env.dev[.properties]
      - optional:file:./service_user/.env[.properties]
      - optional:file:./.env[.properties]
      - optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:${DB_PORT:11223}/postgres
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

server:
  port: 8002
  servlet:
    context-path: /api/v1