apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-product-deploy
  labels:
    app: service-product-deploy
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-product-app
      tier: backend
  template:
    metadata:
      name: service-product-app
      labels:
        app: service-product-app
        tier: backend
    spec:
      containers:
        - name: service-product
          image: fnmain1234/service_product:v1
          ports:
            - containerPort: 8001
          envFrom:
            - secretRef:
                name: service-common