apiVersion: v1
kind: Service

metadata:
  name: service-product
  labels:
    app: service-product-svc
    tier: backend

spec:
  type: NodePort
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30002
  selector:
    app: service-product-app
    tier: backend