apiVersion: v1
kind: Service

metadata:
  name: service-book
  labels:
    app: service-book-svc
    tier: backend

spec:
  type: NodePort
  ports:
    - port: 8002
      targetPort: 8002
      nodePort: 30003
  selector:
    app: service-book-app
    tier: backend